### ISSUE TITLE
Effects of structural connectivity maturation in puberty on mental health

### ISSUE THREAD

**Issue by iliana-karipidis** [ABCD-ReproNim/2022_Project_Month#7]
## Research question(s)

How does pubertal maturation of structural brain connectivity affect mental health?

Bonus question:
Can potential sex differences in structural connectivity development be explained by pubertal level?

## Description

Many mental health problems, such as affective disorders, emerge during puberty, with well-known gender/sex differences in their prevalence and manifestation (Bale & Epperson, 2015). For example, teenage girls are almost three times more likely to experience a depressive episode than boys (Breslau et al., 2017). Structural brain development has also been shown to depend on sex (Kaczkurkin et al. 2018) and pubertal status (Herting & Sowell, 2017). However, it remains unclear how brain maturation during puberty is associated with mental health outcomes. 

The aim of this project is to study how mental health factors relate to developmental trajectories of structural connectivity maturation based on pubertal status instead of chronological age. Brain maturation is guided by sex steroid levels during puberty (Peper & Dahl, 2013) and we can leverage physical and hormonal pubertal measures available in the ABCD Dataset (Cheng et al. 2021) to model how structural connectivity measures depending on pubertal stage influence mental health factors (and vice versa). In addition, it would be interesting to select suitable approaches to estimate sex-specific effects, given that pubertal development deferrs based on natal sex. For example, a recent study showed that at the 1-year follow up assessment of the ABCD study 1.9% of males vs. 13.5% of females had reached late/post pubertal stages (Argabright et al. 2022).

Open Question:
How can we account for the racial/ethnic differences in progression of pubertal development that was recently demonstrated in the ABCD Study sample? (Argabright et al. 2022)

## Tools and algorithms to be used

multidimensional analysis, classification, R, python, pyAFQ

## Suggested keywords/tags

mental health
pubertal status
structural connectivity
DTI
salivary sex hormone levels
sex differences

**Comment by jessicabartley** [comment]
Hi @iliana-karipidis - Nice project proposal! 

I don't see you on our Project Month registration or DUC confirmation list. Have you signed up to participate in Project Month?

**Comment by iliana-karipidis** [comment]
Hi @jessicabartley - thank you, I just signed up!

**Comment by jessicabartley** [comment]
Thanks for the quick reply on this message! 

I just checked your DUC upload and... I'm very sorry to be the bearer of bad news but it looks like your DUC is still awaiting approval. This means you will not be able to access the ABCD dataset until the approval goes through, and this process often takes several weeks. Unfortunately participation in Project Month is limited to individuals who have an approved DUC. NIH provides access to ABCD Data through the DUCs, so without  that, you won’t be able to analyze any data. This is particularly unfortunate because this sounds like a very interesting project.

**Comment by jessicabartley** [comment]
Forgot to tag @iliana-karipidis in my above comment

**Comment by raphaelcuhk** [comment]
It's an interesting question and really appealing to me! It would be quite pity for me to hear @jessicabartley comment. I'm good at coding and could also do some algorithms jobs, maybe we could work together in some days!

**Comment by jessicabartley** [comment]
I agree! It is such a shame! Perhaps once @iliana-karipidis has an approved DUC they can come back to this thread and connect with @raphaelcuhk (and anyone else who is interested) and set up a collaboration to work on it

**Comment by iliana-karipidis** [comment]
I will look into this, I was not aware that our DUC is still pending renewal

**Comment by jessicabartley** [comment]
@iliana-karipidis on the DUC screenshot you uploaded it says "Waiting on Agreement Upload" under Request Status, which typically means your university singing official need to upload their approval before the request gets sent to the NDA. If your DUC is already approved/renewed, however, please send me a message (ingo@abcd-repronim.org) and I would be very happy to invite you to participate in Project Month!

**Comment by jessicabartley** [comment]
Was very sad that we ran into DUC issues with this. It would have been an awesome project to have at Project Month. I'm going to go ahead and close this issue to clean up the space a bit -- but anyone that might be interested in working with @iliana-karipidis on this in the future I encourage reaching out to her!
